### ISSUE TITLE
Fails to launch .cmd files

### ISSUE THREAD

**Issue by gvandegrift** [1337programming/webpack-shell-plugin#22]
As of version 0.4.5 (0.4.4 works correctly), on windows, batch/command files don't work unless you include the .bat/.cmd extension.  This causes problems with running scripts from npm packages in a way that is agnostic of Windows/Linux.  For example, if I have semver installed, there will be both a ./node_modules/.bin/semver (for Linux) and a ./node_modules/.bin/semver.cmd (for Windows).  At my actual command line I should just be able to run semver (without an extension) on either Windows or Linux.  As of 0.4.5, I have to launch it as semver.cmd when on Windows which means I have to switch my webpack code based on platform (which is less than ideal).

Just speculating, but could it have something to do with the switch to child_process.spawn from child_process.exec?

**Comment by gvandegrift** [comment]
This might explain things:  https://nodejs.org/dist/latest-v6.x/docs/api/child_process.html#child_process_spawning_bat_and_cmd_files_on_windows

**Comment by opiepj** [comment]
This probably came from switch to spawn instead of exec. I'll keep the spawn for unix operating systems, but for windows i'll use exec instead.

**Comment by opiepj** [comment]
Could you try with version 0.4.7?

**Comment by gvandegrift** [comment]
Getting the following error now:

`C:\src\health-buyflow\node_modules\webpack-shell-plugin\lib\index.js:196
        this.spreadStdoutAndStdErr(exec(script, puts));
                                                ^

ReferenceError: puts is not defined
    at WebpackShellPlugin.handleScript (C:\src\health-buyflow\node_modules\webpack-shell-plugin\lib\index.js:196:49)
    at Compiler.<anonymous> (C:\src\health-buyflow\node_modules\webpack-shell-plugin\lib\index.js:254:19)
    at Compiler.applyPluginsAsync (C:\src\health-buyflow\node_modules\tapable\lib\Tapable.js:71:13)
    at Compiler.emitAssets (C:\src\health-buyflow\node_modules\webpack\lib\Compiler.js:226:7)
    at Compiler.<anonymous> (C:\src\health-buyflow\node_modules\webpack\lib\Compiler.js:184:10)
    at C:\src\health-buyflow\node_modules\webpack\lib\Compiler.js:403:12
    at Compiler.next (C:\src\health-buyflow\node_modules\tapable\lib\Tapable.js:67:11)
    at Compiler.<anonymous> (C:\src\health-buyflow\node_modules\webpack\lib\CachePlugin.js:40:4)
    at Compiler.applyPluginsAsync (C:\src\health-buyflow\node_modules\tapable\lib\Tapable.js:71:13)
    at Compiler.<anonymous> (C:\src\health-buyflow\node_modules\webpack\lib\Compiler.js:400:9)
    at Compilation.<anonymous> (C:\src\health-buyflow\node_modules\webpack\lib\Compilation.js:577:13)
    at Compilation.applyPluginsAsync (C:\src\health-buyflow\node_modules\tapable\lib\Tapable.js:60:69)
    at Compilation.<anonymous> (C:\src\health-buyflow\node_modules\webpack\lib\Compilation.js:572:10)
    at Compilation.applyPluginsAsync (C:\src\health-buyflow\node_modules\tapable\lib\Tapable.js:60:69)
    at Compilation.<anonymous> (C:\src\health-buyflow\node_modules\webpack\lib\Compilation.js:567:9)
    at Compilation.applyPluginsAsync (C:\src\health-buyflow\node_modules\tapable\lib\Tapable.js:60:69)
    at Compilation.<anonymous> (C:\src\health-buyflow\node_modules\webpack\lib\Compilation.js:563:8)
    at Compilation.applyPluginsAsync (C:\src\health-buyflow\node_modules\tapable\lib\Tapable.js:60:69)
    at Compilation.seal (C:\src\health-buyflow\node_modules\webpack\lib\Compilation.js:525:7)
    at Compiler.<anonymous> (C:\src\health-buyflow\node_modules\webpack\lib\Compiler.js:397:15)
    at C:\src\health-buyflow\node_modules\tapable\lib\Tapable.js:103:11
    at Compilation.<anonymous> (C:\src\health-buyflow\node_modules\webpack\lib\Compilation.js:445:10)
    at C:\src\health-buyflow\node_modules\webpack\lib\Compilation.js:417:12
    at C:\src\health-buyflow\node_modules\webpack\lib\Compilation.js:332:10
    at C:\src\health-buyflow\node_modules\webpack\node_modules\async\lib\async.js:52:16
    at done (C:\src\health-buyflow\node_modules\webpack\node_modules\async\lib\async.js:246:17)
    at C:\src\health-buyflow\node_modules\webpack\node_modules\async\lib\async.js:44:16
    at C:\src\health-buyflow\node_modules\webpack\lib\Compilation.js:332:10
    at C:\src\health-buyflow\node_modules\webpack\node_modules\async\lib\async.js:52:16
    at done (C:\src\health-buyflow\node_modules\webpack\node_modules\async\lib\async.js:246:17)`

**Comment by opiepj** [comment]
This is a duplicate #23 closing.

But @szymonkudzia had made a fix #24 and has been released, see if that clears up the error and refer to #23
