### ISSUE TITLE
stdout error

### ISSUE THREAD

**Issue by wayofthefuture** [1337programming/webpack-shell-plugin#65]
On Windows with most recent package version, I am getting a buffer stdout error:

```
[SERVICES] Error: stdout maxBuffer exceeded
[SERVICES]     at Socket.onChildStdout (child_process.js:328:14)
[SERVICES]     at emitOne (events.js:121:20)
[SERVICES]     at Socket.emit (events.js:211:7)
[SERVICES]     at addChunk (_stream_readable.js:263:12)
[SERVICES]     at readableAddChunk (_stream_readable.js:246:13)
[SERVICES]     at Socket.Readable.push (_stream_readable.js:208:10)
[SERVICES]     at Pipe.onread (net.js:597:20)
```

Any ideas?

**Comment by wayofthefuture** [comment]
Commit added as per fix: https://github.com/SaschaGalley/grunt-phpunit/issues/29

**Comment by rubangarmon** [comment]
I have same issue:

```
RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stdout maxBuffer length exceeded
    at Socket.onChildStdout (child_process.js:354:14)
    at Socket.emit (events.js:203:15)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:265:13)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:94:17)
```
What did you do?
