### ISSUE TITLE
[webpack-cli] TypeError: compiler.plugin is not a function

### ISSUE THREAD

**Issue by zeperto** [1337programming/webpack-shell-plugin#75]
[webpack-cli] TypeError: compiler.plugin is not a function
    at WebpackShellPlugin.apply (E:\xampp\htdocs\transTest\node_modules\webpack-shell-plugin\lib\index.js:236:16)
    at createCompiler (E:\xampp\htdocs\transTest\node_modules\webpack\lib\webpack.js:73:12)
    at create (E:\xampp\htdocs\transTest\node_modules\webpack\lib\webpack.js:134:16)
    at webpack (E:\xampp\htdocs\transTest\node_modules\webpack\lib\webpack.js:142:47)
    at WebpackCLI.f [as webpack] (E:\xampp\htdocs\transTest\node_modules\webpack\lib\index.js:58:16)
    at WebpackCLI.createCompiler (E:\xampp\htdocs\transTest\node_modules\webpack-cli\lib\webpack-cli.js:2191:23)
    at async WebpackCLI.runWebpack (E:\xampp\htdocs\transTest\node_modules\webpack-cli\lib\webpack-cli.js:2321:16)
    at async Command.<anonymous> (E:\xampp\htdocs\transTest\node_modules\webpack-cli\lib\webpack-cli.js:1058:13)
    at async Promise.all (index 1)
    at async Command.<anonymous> (E:\xampp\htdocs\transTest\node_modules\webpack-cli\lib\webpack-cli.js:1672:7)

**Comment by j3soon** [comment]
See #73 for the solution
